Timur katimullin basic ellipsis
linkouth/ui-intership-timur-katimullin pull request #1
Opened 2019-09-30 18:54 UTC by linkouth

Implements basic ellipsis mark up.

2019-10-03 07:33 UTC, vovcyan requested changes

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> -    <title>Welcome to Firebase Hosting</title>
Please add a title for your site

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +            <h1 class="header__header">WORKING
In 1 line

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +            <p class="header__text">We’ve been helping startups launch and grow their businesses.
Move text to next line

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +            <img src='images/Mouse-icon.svg' alt='scrollable' class="header__mouse-logo" />
Please change alt

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +            <p class="container__text"> When you work with us, you are part of a team of committed collaborators.
The same

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +            <h2 class="container__header container__services__header container__header__background_none"><span>Services</span></h2>
Please separate it into 2 lines

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +            <p class="container__text">Before we sign a contract or write a line of code our team will spend the necessary
The same

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +              <img src="images/DesignLogo.svg" class="group__label" alt="design logo" />
The same

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +              <p class="group__text">Our design practice offers a full range of services including branding strategy,
The same

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/index.html
> +              <p class="group__text">Planning and development is iterative. Because we are constantly coding and testing, the
The same

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  padding-top: 8vh;
padding:

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  padding-bottom: 0;
The same

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  background: url('../images/ServicesBG.png');
-image

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  padding-top: 6vh;
Why 6 vh?

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  background: url('../images/WelcomeBG.png');
background-image:

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  letter-spacing: 0.9px;
.9px

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  background-color: darkcyan;
Please use HEX color

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  padding-top: 0vh;
padding:

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +  opacity: 0.5;
.5;

2019-10-03 07:33 UTC, vovcyan commented on basic-ellipsis/public/style/main.css
> +@media only screen and (max-width: 900px) {
Please add media for vertical iPad

2019-10-07 09:13 UTC, vadeneev requested changes

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +          <div class="content_container content_container__without_border content_container__text_secondary_color">
> __without_border
looks like modifier, but used as element  (according to syntax block-name__element_modifier)

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +            <h1 class="header__header">WORKING<br aria-hidden="true">WITH design LAB </h1>
header__title ?

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +        <div class="wrapper wrapper__theme_services">
looks like __theme_services is modifier

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +          <div class="content_container content_container__services content_container__text_secondary_color content_container__border_secondary_color">
`content_container__text_secondary_color content_container__border_secondary_color`
doesn't it look too... atomic ? could we use one color theme for example ?
(it is a question)

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +            <h2 class="content_container__header content_container__services__header content_container__header__without_background"><span>Services</span></h2>
there shouldn't be element of elements, means __element__element
__ = for element
_ = for modifier

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +            <div class="group">
Doesn't this one looks as like as content-container ?
(same stuff but without border and with image)

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/index.html
> +          <div class="content_container content_container__without_border footer__content_container">
can't see where footer block starts

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/style/main.css
> +.content_container__services__header > span {
we should not use elements in BEM, also there is no place for element of element

2019-10-07 09:13 UTC, vadeneev commented on basic-ellipsis/public/style/main.css
> +header {
we should not use element selector in BEM

2019-10-07 12:56 UTC, vovcyan submitted a review, later dismissed

2019-10-08 09:27 UTC, vovcyan approved these changes

2019-10-08 11:13 UTC, vadeneev approved these changes

2019-10-08 13:43 UTC, merged